In [33]:
import numpy as np
import pandas as pd

In [34]:
players = pd.read_csv('Players.csv')

In [35]:
players.head()

,Player,COUNTRY,TEAM,AGE,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,...,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w,SOLD_PRICE
0,Ruturaj Gaikwad,IND,CSK,26,0,Batting,36,36.0,1207.0,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6cr
1,Shivam Dube,IND,CSK,29,0,All rounder,35,33.0,688.0,516.0,...,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0,4cr
2,Ambati Rayudu,IND,CSK,37,0,Batting,188,175.0,4190.0,3296.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.75cr
3,Devon Conway,NZ,CSK,31,0,Batting,7,7.0,252.0,173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1cr
4,Moeen Ali,ENG,CSK,35,0,All rounder,44,42.0,910.0,632.0,...,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0,8cr

In [36]:
players.shape

(182, 53)

In [37]:
players = players.drop(columns = ['TEAM','AGE','SOLD_PRICE'])

In [38]:
players.head()

,Player,COUNTRY,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,HS,Avg,...,B_TInns,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w
0,Ruturaj Gaikwad,IND,0,Batting,36,36.0,1207.0,926.0,101.0,37.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shivam Dube,IND,0,All rounder,35,33.0,688.0,516.0,95.0,24.57,...,11.0,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0
2,Ambati Rayudu,IND,0,Batting,188,175.0,4190.0,3296.0,100.0,28.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Devon Conway,NZ,0,Batting,7,7.0,252.0,173.0,87.0,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Moeen Ali,ENG,0,All rounder,44,42.0,910.0,632.0,93.0,23.33,...,58.0,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0

In [39]:
players

,Player,COUNTRY,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,HS,Avg,...,B_TInns,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w
0,Ruturaj Gaikwad,IND,0,Batting,36,36.0,1207.0,926.0,101.0,37.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shivam Dube,IND,0,All rounder,35,33.0,688.0,516.0,95.0,24.57,...,11.0,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0
2,Ambati Rayudu,IND,0,Batting,188,175.0,4190.0,3296.0,100.0,28.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Devon Conway,NZ,0,Batting,7,7.0,252.0,173.0,87.0,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Moeen Ali,ENG,0,All rounder,44,42.0,910.0,632.0,93.0,23.33,...,58.0,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,Abdul Samad,IND,0,All rounder,25,20.0,226.0,159.0,33.0,14.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,Umran Malik,IND,0,Bowling,17,NaN,NaN,NaN,NaN,NaN,...,8.0,139.0,243.0,0.0,11.0,22.09,10.49,12.64,0.0,0.0
179,Fazalhaq Farooqi,AFG,0,Bowling,3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Jagadeesha Suchith,IND,0,All rounder,22,10.0,70.0,61.0,34.0,17.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,T Natarajan,IND,0,Bowling,35,NaN,NaN,NaN,NaN,NaN,...,4.0,96.0,122.0,0.0,7.0,17.43,7.62,13.71,0.0,0.0

In [40]:
# inserts 'Player_ID' at index 0 (the very first column)
players.insert(0, 'Player_ID', range(1, len(players) + 1))

In [41]:
players.head()

,Player_ID,Player,COUNTRY,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,HS,...,B_TInns,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w
0,1,Ruturaj Gaikwad,IND,0,Batting,36,36.0,1207.0,926.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Shivam Dube,IND,0,All rounder,35,33.0,688.0,516.0,95.0,...,11.0,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0
2,3,Ambati Rayudu,IND,0,Batting,188,175.0,4190.0,3296.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Devon Conway,NZ,0,Batting,7,7.0,252.0,173.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Moeen Ali,ENG,0,All rounder,44,42.0,910.0,632.0,93.0,...,58.0,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0

In [42]:
print(players.columns)

Index(['Player_ID', 'Player', 'COUNTRY', 'CAPTAINCY EXP', 'Paying_Role', 'Mat',
       'Inns', 'Runs', 'BF', 'HS', 'Avg', 'SR', 'NO', '4s', '6s', '0s', '50s',
       '100s', 'TMat', 'TInns', 'TRuns', 'TBF', 'THS', 'TAvg', 'TSR', 'TNO',
       'T4s', 'T6s', 'T0s', 'T50s', 'T100s', 'B_Inns', 'B_Balls', 'B_Runs',
       'B_Maidens', 'B_Wkts', 'B_Avg', 'B_Econ', 'B_SR', 'B_4w', 'B_5w',
       'B_TInns', 'B_TBalls', 'B_TRuns', 'B_TMaidens', 'B_TWkts', 'B_TAvg',
       'B_TEcon', 'B_TSR', 'B_T4w', 'B_T5w'],
      dtype='object')

In [43]:
keep_cols = [
    # Identity
    'Player_ID',
    'Player',
    'Paying_Role',

    # Batting – career
    'Mat', 'Inns', 'Runs', 'Avg', 'SR',

    # Batting – recent (T)
    'TMat', 'TInns', 'TRuns', 'TAvg', 'TSR',

    # Bowling – career
    'B_Inns', 'B_Balls', 'B_Wkts', 'B_Econ',

    # Bowling – recent (T)
    'B_TInns', 'B_TBalls', 'B_TWkts', 'B_TEcon'
]

In [44]:
players_clean = players[keep_cols].copy()

In [45]:
players_clean.head()

,Player_ID,Player,Paying_Role,Mat,Inns,Runs,Avg,SR,TMat,TInns,...,TAvg,TSR,B_Inns,B_Balls,B_Wkts,B_Econ,B_TInns,B_TBalls,B_TWkts,B_TEcon
0,1,Ruturaj Gaikwad,Batting,36,36.0,1207.0,37.72,130.35,9.0,8.0,...,16.88,123.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Shivam Dube,All rounder,35,33.0,688.0,24.57,133.33,13.0,9.0,...,17.50,136.36,13.0,106.0,4.0,9.40,11.0,129.0,5.0,10.05
2,3,Ambati Rayudu,Batting,188,175.0,4190.0,28.9,127.12,6.0,5.0,...,10.50,84.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Devon Conway,Batting,7,7.0,252.0,42,145.66,38.0,35.0,...,45.70,130.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Moeen Ali,All rounder,44,42.0,910.0,23.33,143.99,74.0,64.0,...,22.42,413.47,37.0,554.0,24.0,6.79,58.0,829.0,42.0,8.29

In [46]:
players_clean.shape

(182, 21)

In [47]:
# Fill NaNs with 0 for numeric columns
num_cols = players_clean.select_dtypes(include=['float64', 'int64']).columns
players_clean[num_cols] = players_clean[num_cols].fillna(0)

In [48]:
players_clean.head()

,Player_ID,Player,Paying_Role,Mat,Inns,Runs,Avg,SR,TMat,TInns,...,TAvg,TSR,B_Inns,B_Balls,B_Wkts,B_Econ,B_TInns,B_TBalls,B_TWkts,B_TEcon
0,1,Ruturaj Gaikwad,Batting,36,36.0,1207.0,37.72,130.35,9.0,8.0,...,16.88,123.85,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
1,2,Shivam Dube,All rounder,35,33.0,688.0,24.57,133.33,13.0,9.0,...,17.50,136.36,13.0,106.0,4.0,9.40,11.0,129.0,5.0,10.05
2,3,Ambati Rayudu,Batting,188,175.0,4190.0,28.9,127.12,6.0,5.0,...,10.50,84.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
3,4,Devon Conway,Batting,7,7.0,252.0,42,145.66,38.0,35.0,...,45.70,130.31,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
4,5,Moeen Ali,All rounder,44,42.0,910.0,23.33,143.99,74.0,64.0,...,22.42,413.47,37.0,554.0,24.0,6.79,58.0,829.0,42.0,8.29

In [49]:
players_clean['Paying_Role'] = players_clean['Paying_Role'].str.lower()

players_clean['Paying_Role'] = players_clean['Paying_Role'].replace({
    'batting': 'batsman',
    'bowling': 'bowler',
    'all rounder': 'allrounder',
    'allrounder': 'allrounder'
})

In [31]:
players_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player_ID    182 non-null    int64
 1   Player       182 non-null    object
 2   Paying_Role  182 non-null    object
 3   Mat          182 non-null    int64
 4   Inns         182 non-null    float64
 5   Runs         182 non-null    float64
 6   Avg          126 non-null    object
 7   SR           182 non-null    float64
 8   TMat         182 non-null    float64
 9   TInns        182 non-null    float64
 10  TRuns        182 non-null    float64
 11  TAvg         182 non-null    float64
 12  TSR          182 non-null    float64
 13  B_Inns       182 non-null    float64
 14  B_Balls      182 non-null    float64
 15  B_Wkts       182 non-null    float64
 16  B_Econ       182 non-null    float64
 17  B_TInns      182 non-null    float64
 18  B_TBalls     182 non-null    float64
 19  B_TWkts      182 non-null    float64
 20  B_TEcon      182 non-null    float64
dtypes: float64(16), int64(2), object(3)
memory usage: 30.0+ KB

In [50]:
players_clean['Avg'] = pd.to_numeric(players_clean['Avg'], errors='coerce')

In [51]:
players_clean['Avg'] = players_clean['Avg'].fillna(0)

In [57]:
players_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player_ID     182 non-null    int64
 1   Player        182 non-null    object
 2   Playing_Role  182 non-null    category
 3   Mat           182 non-null    int64
 4   Inns          182 non-null    float64
 5   Runs          182 non-null    float64
 6   Avg           182 non-null    float64
 7   SR            182 non-null    float64
 8   TMat          182 non-null    float64
 9   TInns         182 non-null    float64
 10  TRuns         182 non-null    float64
 11  TAvg          182 non-null    float64
 12  TSR           182 non-null    float64
 13  B_Inns        182 non-null    float64
 14  B_Balls       182 non-null    float64
 15  B_Wkts        182 non-null    float64
 16  B_Econ        182 non-null    float64
 17  B_TInns       182 non-null    float64
 18  B_TBalls      182 non-null    float64
 19  B_TWkts       182 non-null    float64
 20  B_TEcon       182 non-null    float64
dtypes: category(1), float64(17), int64(2), object(1)
memory usage: 28.9+ KB

In [53]:
players_clean = players_clean.rename(columns={'Paying_Role': 'Playing_Role'})

In [56]:
players_clean['Playing_Role'] = players_clean['Playing_Role'].astype('category')

In [58]:
players_clean.to_csv("player_stats_clean.csv", index=False)